ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_FULL_LOAD_FACT_PROCESS_RULE_STATUS SUSPEND;

CREATE OR REPLACE TASK DEMO_DB.DEMO_SCHEMA.TSK_FULL_LOAD_FACT_PROCESS_RULE_STATUS
    WAREHOUSE = SOSTENIBILIDAD_PIPELINE_WH
    SCHEDULE = 'USING CRON 45 11 * * 6 Europe/Madrid'
AS
    CALL DEMO_DB.DEMO_SCHEMA.PR_FULL_LOAD_FACT_PROCESS_RULE_STATUS();

ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_FULL_LOAD_FACT_PROCESS_RULE_STATUS RESUME;