ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS SUSPEND;

CREATE OR REPLACE TASK DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS
    WAREHOUSE = SOSTENIBILIDAD_PIPELINE_WH
    SCHEDULE = '60 MINUTE'
AS
    CALL DEMO_DB.DEMO_SCHEMA.PR_LOAD_FACT_PROCESS_RULE_STATUS();

ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS RESUME;