name: 'dbt_poc' 
version: '1.0.0'
config-version: 2

profile: 'dbt_poc'

model-paths: ["models"]

models:
  dbt_poc:
    +materialized: view
    silver:
      +materialized: incremental
      +schema: silver_layer
    gold:
      +schema: gold_layer

snapshots:
  dbt_poc: snapshots