CREATE OR REPLACE PROCEDURE DEMO_DB.DEMO_SCHEMA.PR_CREATE_TMP_FACT_PROCESS_RULE_STATUS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS 
$$
BEGIN


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_DIM_RAW (
	ID_RAW NUMBER(38,0),
	ID_BRAND NUMBER(38,0),
	ID_SEASON NUMBER(38,0),
	ID_SECTION NUMBER(38,0),
	ID_PRODUCT NUMBER(38,0),
	IS_NEW BOOLEAN,
	MIN_ID_SEASON NUMBER(38,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_DIM_ARTICLE (
	ID_ARTICLE NUMBER(38,0),
	ID_BRAND NUMBER(38,0),
	ID_SEASON NUMBER(38,0),
	ID_SECTION NUMBER(38,0),
	ID_PRODUCT NUMBER(38,0),
	IS_NEW BOOLEAN,
	MIN_ID_SEASON NUMBER(38,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_DIM_ARTICLE_COLOR (
	COD_ARTICLE NUMBER(38,0),
	ID_ARTICLE NUMBER(38,0),
	ID_COLOR NUMBER(38,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_FACT_RAW_ORDER (
	ID_ORDER NUMBER(38,0),
	ID_RAW_MATERIAL_ORDER NUMBER(38,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_EXTRACT_FACT_PROCESS_RULE_STATUS (
	EVENT_NAME VARCHAR(16777216),
	EVENT_PK VARCHAR(16777216),
	EVENT_ID VARCHAR(16777216),
	INGEST_DATE TIMESTAMP_LTZ(9),
	EVENT_DATE TIMESTAMP_LTZ(9),
	NEXT_EVENT_DATE TIMESTAMP_LTZ(9),
	ID_PROCESS_RULE NUMBER(38,0),
	ID_PROCESS_STATUS NUMBER(38,0),
	ID_ARTICLE NUMBER(38,0),
	ID_RAW NUMBER(38,0),
	ID_COLOR NUMBER(38,0),
	ID_DOCUMENT_TYPE NUMBER(38,0),
	ID_SUPPLIER NUMBER(38,0),
	ID_PROCESS_STATUS_REASON NUMBER(38,0),
	ID_NEGOTIATION_ORDER NUMBER(38,0),
	ID_ORDER NUMBER(38,0),
	ID_BUYING_CENTER NUMBER(38,0),
	ID_RULE_LEVEL NUMBER(38,0),
	ID_SUSTAINABLE_MATERIAL_GROUP NUMBER(38,0),
	DELIVERY_NUMBER NUMBER(38,0),
	ORDER_NUMBER NUMBER(38,0),
	DEADLINE_DATE TIMESTAMP_TZ(9),
	DATE_CREATED TIMESTAMP_TZ(9),
	URGENT_DATE TIMESTAMP_TZ(9),
	IS_URGENT NUMBER(38,0),
	IS_FIRST_ORDER NUMBER(38,0),
	IS_SELF_DECLARATION NUMBER(2,0),
	DOCUMENTLIST VARIANT,
	MATERIALS VARIANT,
	COMPOSITION_CODE VARIANT,
	COMPOSITION_TYPE_CODE VARIANT,
	GARMENT_ZONE_CODE VARIANT,
	SUSTAINABLE_MATERIAL_CODE NUMBER(38,0),
	RANK_ORDER NUMBER(18,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_TRANSFORM_1_FACT_PROCESS_RULE_STATUS (
	ID_PROCESS_RULE NUMBER(38,0),
	ID_PROCESS_STATUS NUMBER(38,0),
	ID_ARTICLE NUMBER(38,0),
	ID_RAW NUMBER(38,0),
	ID_COLOR NUMBER(38,0),
	ID_DOCUMENT_TYPE NUMBER(38,0),
	ID_SUPPLIER NUMBER(38,0),
	ID_PROCESS_STATUS_REASON NUMBER(38,0),
	ID_NEGOTIATION_ORDER NUMBER(38,0),
	ID_ORDER NUMBER(38,0),
	ID_BUYING_CENTER NUMBER(38,0),
	ID_RULE_LEVEL NUMBER(38,0),
	ID_SUSTAINABLE_MATERIAL_GROUP NUMBER(38,0),
	DELIVERY_NUMBER NUMBER(38,0),
	ORDER_NUMBER NUMBER(38,0),
	DEADLINE_DATE TIMESTAMP_TZ(9),
	DATE_CREATED TIMESTAMP_TZ(9),
	URGENT_DATE TIMESTAMP_TZ(9),
	IS_URGENT NUMBER(38,0),
	IS_FIRST_ORDER NUMBER(38,0),
	IS_SELF_DECLARATION NUMBER(2,0),
	ID_DOCUMENT_PROCESS NUMBER(38,0),
	ID_COMPOSITION NUMBER(38,0),
	ID_COMPOSITION_TYPE NUMBER(38,0),
	ID_PRODUCT_ZONE NUMBER(38,0),
	ID_SUSTAINABLE_MATERIAL NUMBER(38,0),
	ID_SUBARTICLE NUMBER(38,0),
	IS_SUBARTICLE NUMBER(1,0),
	IS_MMPP NUMBER(1,0),
	IS_MATERIAL_ANALYTICS_CANDIDATE NUMBER(1,0),
	START_DATE TIMESTAMP_TZ(9),
	END_DATE TIMESTAMP_TZ(9),
	IS_ACTUAL NUMBER(1,0),
	INGEST_DATE TIMESTAMP_LTZ(9),
	EVENT_METADATA OBJECT,
	ACTION VARCHAR(16777216),
	RANK_ORDER NUMBER(18,0)
);


CREATE OR REPLACE TEMPORARY TABLE DEMO_DB.DEMO_SCHEMA.TMP_TRANSFORM_2_FACT_PROCESS_RULE_STATUS (
	ID_PROCESS_RULE NUMBER(38,0),
	ID_DOCUMENT_PROCESS NUMBER(38,0),
	ID_COMPOSITION NUMBER(38,0),
	ID_COMPOSITION_TYPE NUMBER(38,0),
	ID_PRODUCT_ZONE NUMBER(38,0),
	COD_ARTICLE NUMBER(38,0),
	ID_ARTICLE NUMBER(38,0),
	ID_RAW NUMBER(38,0),
	ID_COLOR NUMBER(38,0),
	ID_DOCUMENT_TYPE NUMBER(38,0),
	ID_SUPPLIER NUMBER(38,0),
	ID_PROCESS_STATUS NUMBER(38,0),
	ID_PROCESS_STATUS_REASON NUMBER(38,0),
	ID_NEGOTIATION_ORDER NUMBER(38,0),
	ID_ORDER NUMBER(38,0),
	ID_BUYING_CENTER NUMBER(38,0),
	ID_RULE_LEVEL NUMBER(38,0),
	ID_SUSTAINABLE_MATERIAL NUMBER(38,0),
	ID_SUSTAINABLE_MATERIAL_GROUP NUMBER(38,0),
	DELIVERY_NUMBER NUMBER(38,0),
	ORDER_NUMBER NUMBER(38,0),
	ID_BRAND NUMBER(38,0),
	ID_SECTION NUMBER(38,0),
	ID_SEASON NUMBER(38,0),
	ID_PRODUCT NUMBER(38,0),
	ID_RAW_MATERIAL_ORDER NUMBER(38,0),
	DEADLINE_DATE TIMESTAMP_TZ(9),
	DATE_CREATED TIMESTAMP_TZ(9),
	URGENT_DATE TIMESTAMP_TZ(9),
	IS_URGENT NUMBER(38,0),
	IS_FIRST_ORDER NUMBER(38,0),
	IS_MMPP NUMBER(1,0),
	START_DATE TIMESTAMP_TZ(9),
	END_DATE TIMESTAMP_TZ(9),
	IS_ACTUAL NUMBER(1,0),
	ID_SUBARTICLE NUMBER(38,0),
	IS_SUBARTICLE NUMBER(1,0),
	IS_MATERIAL_ANALYTICS_CANDIDATE NUMBER(1,0),
	IS_SELF_DECLARATION NUMBER(2,0),
	EVENT_METADATA OBJECT,
	INGEST_DATE TIMESTAMP_LTZ(9),
	ACTION VARCHAR(16777216),
	RANK_ORDER NUMBER(18,0)
);
END;
$$;