ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS SUSPEND;

CREATE OR REPLACE TASK DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS
WAREHOUSE = SOSTENIBILIDAD_PIPELINE_WH
SCHEDULE = 'USING CRON 52 4-17 * * * Europe/Madrid'
WHEN SYSTEM$STREAM_HAS_DATA('DEMO_DB.DEMO_SCHEMA.S_ENTITY_FACT_PROCESS_RULE_STATUS')
AS
CALL DEMO_DB.DEMO_SCHEMA.PR_LOAD_FACT_PROCESS_RULE_STATUS('INCREMENTAL');

ALTER TASK IF EXISTS DEMO_DB.DEMO_SCHEMA.TSK_LOAD_FACT_PROCESS_RULE_STATUS RESUME
;    